---

- name: Populate services facts
  ansible.builtin.service_facts:
  # gathering service facts can be slow, only do so after install / upgrade
  when: rke2_version != installed_version

- name: Set the Active Server variable
  ansible.builtin.set_fact:
    active_server: "{{ active_servers | first }}"
  vars:
    query: "[?value.ansible_facts.services.\"rke2-server.service\".state == 'running' && contains(value.group_names, '{{ rke2_servers_group_name }}')].key"
    # requires Python jmespath module
    active_servers: "{{ hostvars | dict2items | community.general.json_query(query) }}"
