---

- name: Restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted

- name: Restart systemd-sysctl
  ansible.builtin.service:
    state: restarted
    name: systemd-sysctl

- name: Config file changed
  ansible.builtin.set_fact:
    rke2_restart_needed: true

- name: RKE2 version changed
  ansible.builtin.set_fact:
    rke2_restart_needed: true
    rke2_version_changed: true

- name: Service (re)started
  ansible.builtin.set_fact:
    rke2_restart_needed: false
    rke2_version_changed: false
